#!/bin/sh
set -e
if [ "$1" = remove ] || [ "$1" = deconfigure ]; then
    if [ -d /run/systemd/system ]; then
        systemctl disable --now hostsfile-dyndns-updater.service || true
    fi
fi
exit 0
